name: opsd_weather_data

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.6
  - requests
  - pandas=0.23.4
  - geopandas
  - jupyter
  - openpyxl  # pandas: excel i/o
  - ruamel.yaml<=0.15
  - xlrd  # pandas: excel i/o
  - tqdm
  - pip:
    - gsee==0.2.0
