name: opsd_weather_data

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.6
  - requests
  - pandas=0.23.4
  - geopandas
  - jupyter
  - openpyxl=2.5.5  # pandas: excel i/o; v2.5.6 produces error
  - ruamel.yaml<=0.15
  - xlrd  # pandas: excel i/o
  - tqdm
  - joblib
  - pyyaml
  - pip:
    - gsee==0.2.0
